import type { Product, Category } from './types';
import { Cog, Car, Zap, Wind, Snowflake, Filter } from 'lucide-react';

export const categories: Category[] = [
  { id: 'cat-01', name: 'Engine Parts', slug: 'engine-parts', icon: Cog, description: 'Keep your engine running smoothly with our high-quality parts.' },
  { id: 'cat-02', name: 'Brakes', slug: 'brakes', icon: Car, description: 'Ensure your safety with our reliable brake pads, rotors, and calipers.' },
  { id: 'cat-03', name: 'Suspension', slug: 'suspension', icon: Zap, description: 'Improve your ride comfort and handling with our suspension components.' },
  { id: 'cat-04', name: 'Exhaust Systems', slug: 'exhaust-systems', icon: Wind, description: 'Upgrade your performance and sound with our exhaust systems.' },
  { id: 'cat-05', name: 'Cooling', slug: 'cooling', icon: Snowflake, description: 'Prevent overheating with our radiators, water pumps, and thermostats.' },
  { id: 'cat-06', name: 'Filters', slug: 'filters', icon: Filter, description: 'Maintain your vehicle\'s health with our range of oil, air, and fuel filters.' },
];

export const products: Product[] = [
  {
    id: 'P-001',
    name: 'High-Performance Spark Plugs (Set of 4)',
    slug: 'high-performance-spark-plugs',
    description: 'Boost your engine\'s performance and fuel efficiency with these premium iridium spark plugs. Designed for a longer lifespan and consistent ignition.',
    price: 59.99,
    category: 'Engine Parts',
    brand: 'Autopower',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    specs: { 'Material': 'Iridium', 'Compatibility': 'Most 4-cylinder engines', 'Lifespan': 'Up to 100,000 miles' },
    reviews: [
      { id: 'R-001', author: 'John D.', rating: 5, title: 'Great upgrade!', comment: 'Noticed a smoother idle and better throttle response immediately.', date: '2023-10-15' },
    ],
    rating: 5,
    stock: 150,
  },
  {
    id: 'P-002',
    name: 'Ceramic Brake Pad Set (Front)',
    slug: 'ceramic-brake-pad-set-front',
    description: 'Experience superior stopping power and low dust with our advanced ceramic brake pads. Engineered for quiet, reliable performance.',
    price: 89.99,
    category: 'Brakes',
    brand: 'StopSure',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    specs: { 'Compound': 'Ceramic', 'Position': 'Front', 'Includes': 'Pads and hardware' },
    reviews: [
      { id: 'R-002', author: 'Sarah K.', rating: 5, title: 'Quiet and clean', comment: 'Big improvement over my old metallic pads. Very little dust on my wheels now.', date: '2023-11-20' },
    ],
    rating: 5,
    stock: 80,
  },
  {
    id: 'P-003',
    name: 'Performance Air Filter',
    slug: 'performance-air-filter',
    description: 'Unleash hidden horsepower and torque with this high-flow, washable air filter. Designed to increase airflow while providing excellent filtration.',
    price: 45.50,
    category: 'Filters',
    brand: 'BreatheEasy',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Material': 'Cotton Gauze', 'Washable': 'Yes', 'Fitment': 'Direct OEM replacement' },
    reviews: [],
    rating: 4.5,
    stock: 200,
  },
  {
    id: 'P-004',
    name: 'Adjustable Coilover Suspension Kit',
    slug: 'adjustable-coilover-kit',
    description: 'Take full control of your vehicle\'s stance and handling. This coilover kit offers adjustable ride height and damping for the perfect balance of performance and comfort.',
    price: 899.00,
    category: 'Suspension',
    brand: 'RideControl',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    specs: { 'Adjustment': '32-way Damping', 'Height Drop': '1-3 inches', 'Spring Rate': '8k Front / 6k Rear' },
    reviews: [
      { id: 'R-003', author: 'Mike T.', rating: 4, title: 'Great for the track', comment: 'Awesome handling, a bit stiff for daily driving but that\'s expected.', date: '2023-09-05' },
    ],
    rating: 4,
    stock: 25,
  },
  {
    id: 'P-005',
    name: 'Aluminum Performance Radiator',
    slug: 'aluminum-performance-radiator',
    description: 'Keep your engine cool under pressure. This all-aluminum radiator offers a significant improvement in cooling capacity over stock units.',
    price: 320.00,
    category: 'Cooling',
    brand: 'CoolRun',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Core': '2-Row', 'Material': 'T-6061 Aluminum', 'Includes': 'Radiator cap' },
    reviews: [],
    rating: 4.8,
    stock: 40,
  },
  {
    id: 'P-006',
    name: 'Stainless Steel Cat-Back Exhaust',
    slug: 'stainless-cat-back-exhaust',
    description: 'Upgrade your vehicle with a deep, aggressive exhaust note and improved performance. Made from T-304 stainless steel for durability.',
    price: 650.00,
    category: 'Exhaust Systems',
    brand: 'SoundFlow',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Material': 'T-304 Stainless Steel', 'Piping Diameter': '3 inches', 'Tip Style': 'Dual 4-inch tips' },
    reviews: [],
    rating: 4.7,
    stock: 30,
  },
  {
    id: 'P-007',
    name: 'Synthetic Engine Oil - 5 Quart',
    slug: 'synthetic-engine-oil',
    description: 'Protect your engine with our advanced full synthetic motor oil. Provides excellent protection against wear, heat, and breakdown.',
    price: 38.99,
    category: 'Engine Parts',
    brand: 'Autopower',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Viscosity': '5W-30', 'Type': 'Full Synthetic', 'Volume': '5 Quarts' },
    reviews: [],
    rating: 4.9,
    stock: 300,
  },
  {
    id: 'P-008',
    name: 'Premium Oil Filter',
    slug: 'premium-oil-filter',
    description: 'Pair with our synthetic oil for maximum engine protection. High-capacity filter media captures more contaminants.',
    price: 12.99,
    category: 'Filters',
    brand: 'Autopower',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Type': 'Spin-on', 'Media': 'Synthetic Blend', 'Gasket': 'Silicone' },
    reviews: [],
    rating: 4.8,
    stock: 500,
  },
];
