
import type { Product, Category } from './types';
import { Cog, Car, Zap, Wind, Snowflake, Filter, Lightbulb, GitBranch } from 'lucide-react';

export const categories: Category[] = [
  { id: 'cat-01', name: 'Engine Parts', slug: 'engine-parts', icon: Cog, description: 'Keep your engine running smoothly with our high-quality parts.' },
  { id: 'cat-02', name: 'Brakes', slug: 'brakes', icon: Car, description: 'Ensure your safety with our reliable brake pads, rotors, and calipers.' },
  { id: 'cat-03', name: 'Suspension', slug: 'suspension', icon: Zap, description: 'Improve your ride comfort and handling with our suspension components.' },
  { id: 'cat-04', name: 'Exhaust Systems', slug: 'exhaust-systems', icon: Wind, description: 'Upgrade your performance and sound with our exhaust systems.' },
  { id: 'cat-05', name: 'Cooling', slug: 'cooling', icon: Snowflake, description: 'Prevent overheating with our radiators, water pumps, and thermostats.' },
  { id: 'cat-06', name: 'Filters', slug: 'filters', icon: Filter, description: 'Maintain your vehicle\'s health with our range of oil, air, and fuel filters.' },
  { id: 'cat-07', name: 'Lighting', slug: 'lighting', icon: Lightbulb, description: 'See and be seen with our premium automotive lighting solutions.' },
  { id: 'cat-08', name: 'Transmission', slug: 'transmission', icon: GitBranch, description: 'Ensure smooth gear shifts with our quality transmission parts.' },
];

export const products: Product[] = [
  {
    id: 'P-001',
    name: 'High-Performance Spark Plugs (Set of 4)',
    slug: 'high-performance-spark-plugs',
    description: 'Boost your engine\'s performance and fuel efficiency with these premium iridium spark plugs. Designed for a longer lifespan and consistent ignition.',
    price: 59.99,
    category: 'Engine Parts',
    brand: 'NGK',
    images: ['https://images.unsplash.com/photo-1744555879409-3ae34f39eb39?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxFbmdpbmUlMjBQYXJ0cyUyMGF1dG8lMjBwYXJ0fGVufDB8fHx8MTc1NTg1NDM2Nnww&ixlib=rb-4.1.0&q=80&w=1080', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    specs: { 'Material': 'Iridium', 'Compatibility': 'Most 4-cylinder engines', 'Lifespan': 'Up to 100,000 miles' },
    reviews: [
      { id: 'R-001', author: 'John D.', rating: 5, title: 'Great upgrade!', comment: 'Noticed a smoother idle and better throttle response immediately.', date: '2023-10-15' },
    ],
    rating: 5,
    stock: 150,
  },
  {
    id: 'P-002',
    name: 'Brembo Ceramic Brake Pad Set (Front)',
    slug: 'brembo-ceramic-brake-pad-set-front',
    description: 'Experience superior stopping power and low dust with these Brembo ceramic brake pads. Engineered for quiet, reliable performance.',
    price: 99.99,
    category: 'Brakes',
    brand: 'Brembo',
    images: ['https://images.unsplash.com/photo-1653130891925-b12798e271f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxCcmFrZXMlMjBhdXRvJTIwcGFydHxlbnwwfHx8fDE3NTU4NTQzNjV8MA&ixlib=rb-4.1.0&q=80&w=1080', 'https://placehold.co/600x600.png'],
    specs: { 'Compound': 'Ceramic', 'Position': 'Front', 'Includes': 'Pads and hardware' },
    reviews: [
      { id: 'R-002', author: 'Sarah K.', rating: 5, title: 'Quiet and clean', comment: 'Big improvement over my old metallic pads. Very little dust on my wheels now.', date: '2023-11-20' },
    ],
    rating: 5,
    stock: 80,
  },
  {
    id: 'P-003',
    name: 'K&N High-Flow Air Filter',
    slug: 'kn-high-flow-air-filter',
    description: 'Unleash hidden horsepower and torque with this high-flow, washable air filter from K&N. Designed to increase airflow while providing excellent filtration.',
    price: 65.50,
    category: 'Filters',
    brand: 'K&N',
    images: ['https://images.unsplash.com/photo-1624421706776-5ca0151e836a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxGaWx0ZXJzJTIwYXV0byUyMHBhcnR8ZW58MHx8fHwxNzU1ODU0MzY1fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    specs: { 'Material': 'Cotton Gauze', 'Washable': 'Yes', 'Fitment': 'Direct OEM replacement' },
    reviews: [],
    rating: 4.8,
    stock: 200,
  },
  {
    id: 'P-004',
    name: 'Monroe Quick-Strut Assembly',
    slug: 'monroe-quick-strut-assembly',
    description: 'Restore your vehicle\'s factory ride height and handling with this complete strut assembly from Monroe. Includes strut, coil spring, and mount.',
    price: 189.99,
    category: 'Suspension',
    brand: 'Monroe',
    images: ['https://images.unsplash.com/photo-1632656687740-c83b67a55854?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxTdXNwZW5zaW9uJTIwYXV0byUyMHBhcnR8ZW58MHx8fHwxNzU1ODU0MzY1fDA&ixlib=rb-4.1.0&q=80&w=1080', 'https://placehold.co/600x600.png'],
    specs: { 'Type': 'Complete Assembly', 'Position': 'Front Left', 'Pre-assembled': 'Yes' },
    reviews: [
      { id: 'R-003', author: 'Mike T.', rating: 5, title: 'Like new again!', comment: 'My car rides like it just came from the factory. Easy to install.', date: '2023-09-05' },
    ],
    rating: 5,
    stock: 25,
  },
  {
    id: 'P-005',
    name: 'Denso OEM Replacement Radiator',
    slug: 'denso-oem-radiator',
    description: 'Keep your engine cool with this high-quality OEM replacement radiator from Denso. Designed for a perfect fit and reliable performance.',
    price: 150.00,
    category: 'Cooling',
    brand: 'Denso',
    images: ['https://images.unsplash.com/photo-1562509048-6196fbce23de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8Q29vbGluZyUyMGF1dG8lMjBwYXJ0fGVufDB8fHx8MTc1NTg1NDM2NXww&ixlib=rb-4.1.0&q=80&w=1080'],
    specs: { 'Core': '1-Row', 'Material': 'Aluminum/Plastic', 'Fitment': 'OEM Specific' },
    reviews: [],
    rating: 4.9,
    stock: 40,
  },
  {
    id: 'P-006',
    name: 'MagnaFlow Stainless Steel Cat-Back Exhaust',
    slug: 'magnaflow-cat-back-exhaust',
    description: 'Upgrade your vehicle with a deep, smooth exhaust note and improved performance. Made from T-409 stainless steel for durability.',
    price: 750.00,
    category: 'Exhaust Systems',
    brand: 'MagnaFlow',
    images: ['https://images.unsplash.com/photo-1729843606560-e41b0be7fc7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxFeGhhdXN0JTIwU3lzdGVtcyUyMGF1dG8lMjBwYXJ0fGVufDB8fHx8MTc1NTg1NDM2NXww&ixlib=rb-4.1.0&q=80&w=1080'],
    specs: { 'Material': 'T-409 Stainless Steel', 'Piping Diameter': '2.5 inches', 'Tip Style': 'Dual 4-inch tips' },
    reviews: [],
    rating: 4.7,
    stock: 30,
  },
  {
    id: 'P-007',
    name: 'Mobil 1 Full Synthetic Engine Oil - 5 Quart',
    slug: 'mobil-1-synthetic-engine-oil',
    description: 'Protect your engine with Mobil 1 advanced full synthetic motor oil. Provides excellent protection against wear, heat, and breakdown.',
    price: 42.99,
    category: 'Engine Parts',
    brand: 'Mobil 1',
    images: ['https://images.unsplash.com/photo-1720670996738-f8d12d3aba17?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxFbmdpbmUlMjBQYXJ0cyUyMGF1dG8lMjBwYXJ0fGVufDB8fHx8MTc1NTg1NDM2Nnww&ixlib=rb-4.1.0&q=80&w=1080'],
    specs: { 'Viscosity': '5W-30', 'Type': 'Full Synthetic', 'Volume': '5 Quarts' },
    reviews: [],
    rating: 4.9,
    stock: 300,
  },
  {
    id: 'P-008',
    name: 'Bosch Premium Oil Filter',
    slug: 'bosch-premium-oil-filter',
    description: 'Pair with synthetic oil for maximum engine protection. High-capacity filter media captures more contaminants.',
    price: 15.99,
    category: 'Filters',
    brand: 'Bosch',
    images: ['https://images.unsplash.com/photo-1558530755-e4785fddbe89?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxGaWx0ZXJzJTIwYXV0byUyMHBhcnR8ZW58MHx8fHwxNzU1ODU0MzY1fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    specs: { 'Type': 'Spin-on', 'Media': 'Synthetic Blend', 'Gasket': 'Silicone' },
    reviews: [],
    rating: 4.8,
    stock: 500,
  },
   {
    id: 'P-009',
    name: 'Philips X-tremeVision Pro150 Headlight Bulbs (H11)',
    slug: 'philips-xtremevision-headlight-bulbs',
    description: 'See up to 150% more on the road with these advanced halogen headlight bulbs. A direct replacement for standard H11 bulbs.',
    price: 49.99,
    category: 'Lighting',
    brand: 'Philips',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Bulb Type': 'H11', 'Technology': 'Halogen', 'Kelvin': '3400K' },
    reviews: [],
    rating: 4.7,
    stock: 120,
  },
  {
    id: 'P-010',
    name: 'Gates Timing Belt Kit with Water Pump',
    slug: 'gates-timing-belt-kit',
    description: 'Complete timing system replacement kit from Gates, a leader in aftermarket parts. Includes timing belt, tensioner, idlers, and water pump.',
    price: 220.50,
    category: 'Engine Parts',
    brand: 'Gates',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Compatibility': 'Specific to vehicle', 'Includes': 'Belt, tensioner, pulleys, water pump, gaskets', 'Warranty': 'Limited Lifetime' },
    reviews: [],
    rating: 4.9,
    stock: 50,
  },
  {
    id: 'P-011',
    name: 'Valvoline MaxLife ATF - 1 Gallon',
    slug: 'valvoline-maxlife-atf',
    description: 'Full synthetic automatic transmission fluid suitable for a wide range of new and high-mileage vehicles. Conditions seals to prevent leaks.',
    price: 35.99,
    category: 'Transmission',
    brand: 'Valvoline',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Type': 'Full Synthetic ATF', 'Volume': '1 Gallon', 'Application': 'Multi-Vehicle' },
    reviews: [],
    rating: 4.8,
    stock: 90,
  },
  {
    id: 'P-012',
    name: 'Power Stop Z23 Evolution Sport Brake Kit',
    slug: 'power-stop-z23-brake-kit',
    description: 'A complete brake upgrade kit including drilled & slotted rotors and carbon-fiber ceramic pads for improved cooling and stopping power.',
    price: 299.99,
    category: 'Brakes',
    brand: 'Power Stop',
    images: ['https://placehold.co/600x600.png'],
    specs: { 'Position': 'Front', 'Includes': '2 Rotors, 4 Pads, Hardware', 'Rotor Style': 'Drilled & Slotted' },
    reviews: [],
    rating: 4.6,
    stock: 45,
  },
];

    